### ISSUE TITLE
Was there an announcement that i686 would disappear for Centos 6?

### ISSUE THREAD

**Issue by jhfrontz** [iusrepo/announce#17]
```
https://repo.ius.io/6/i386/repodata/repomd.xml: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 404 Not Found"
Trying other mirror.
```

**Comment by carlwgeorge** [comment]
This was part of our infrastructure refresh last year, which was announced [here](https://github.com/iusrepo/announce/issues/13).  It was discussed in detail [here](https://github.com/iusrepo/infrastructure/issues/14#issuecomment-507051198).
