### ISSUE TITLE
Deprecation of legacy ius-release.rpm redirect links

### ISSUE THREAD

**Issue by carlwgeorge** [iusrepo/announce#18]
IUS has always maintained links that get users the latest release of the ius-release package.  Currently those links are served by our CDN.

* https://repo.ius.io/ius-release-el6.rpm
* https://repo.ius.io/ius-release-el7.rpm

Before we started using the ius.io domain, we pointed users to different URLs.

* https://rhel6.iuscommunity.org/ius-release.rpm
* https://rhel7.iuscommunity.org/ius-release.rpm
* https://centos6.iuscommunity.org/ius-release.rpm
* https://centos7.iuscommunity.org/ius-release.rpm

The server handling the *.iuscommunity.org redirects will be decommissioned on 2020-06-01.  The website has pointed users to the new URLs for some time now.  Please update any automation, scripts, or notes that is still reference the old URLs.

**Comment by LukeHandle** [comment]
:wave: Carl!

Hope you're well. Do you still see lots of traffic to them? I'm guessing so if they nicely redirect. People won't notice unless things break.
Is it worth doing a soft-error for the last week where the URLs just return a brief "this is being decommed, see Issue #18?

**Comment by carlwgeorge** [comment]
Howdy Luke!  That's not a bad idea, and could help prevent people raising new issues for it.  On 2020-05-18 (two weeks before the server decommission) I'll disable the redirects and return something similar to the string you're suggesting.

**Comment by carlwgeorge** [comment]
I have disabled the redirects and the old domains now return a link to this issue.

**Comment by broomcms** [comment]
Please keep in mind those changes impacts automated build tools. It's really slowing us down. I hate changes with no legacy. I really don't understand why a 301 redirect can't be used when needed. What’s the harm in a 301 anyway? Why intentionally break things? I can't believe you thought that was a good idea ...

**Comment by lciamp** [comment]
this just broke the builds for all of our dashboards. :/ all good now, but yeah. 301.

**Comment by Jackenmen** [comment]
The 301 was there for quite some time, but since it was redirecting, most people didn't know there's a new repo url and this domain will eventually (iirc, server is decommissioned in two weeks) be abandoned so there needs to be something that will push depending on it to update it.

**Comment by inflatador** [comment]
When it's gone, maybe a 410 is appropriate?
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/410

**Comment by carlwgeorge** [comment]
Issues in this [repository](https://github.com/iusrepo/announce) are specifically used to announce [package retirements](https://ius.io/faq#how-do-i-know-when-an-ius-package-is-being-retired) and other major changes.  If you use IUS, I recommend watching this repository so you are notified of upcoming changes.  Users who were watching this repository knew about these new URLs [over a year ago](https://github.com/iusrepo/announce/issues/13).  About the [same time](https://github.com/iusrepo/infrastructure/issues/14#issuecomment-488866147), the legacy URLs were reconfigured as 301 redirects.  Any users watching this repository who hadn't changed yet got a reminder when this issue was created a month ago.

To avoid continued off-topic notifications being sent to users who are watching this repository, I'm going to lock this issue.  Please follow the [instructions in our FAQ](https://ius.io/faq#how-can-i-report-an-issue-with-an-ius-package) if you need to report issues in the future.
