### ISSUE TITLE
EOL notice for RHEL/CentOS 6 packages

### ISSUE THREAD

**Issue by carlwgeorge** [iusrepo/announce#24]
RHEL 6 and CentOS 6 are now [EOL](https://access.redhat.com/support/policy/updates/errata#Life_Cycle_Dates).  In approximately one month, all IUS EL6 packages will move to https://vault.ius.io and will no longer be maintained.

**Comment by jeffsheltren** [comment]
IUS EL6 packages have been moved to the archive.
